Add DateStringCompat class for some HTC devices bug.
- Some HTC devices return wrong formatted text from DateFormat.
  ex. DateFormat.format("MM月DD日", new Date("2013/1/25"))
    => expected:<01月25[日]> but was:<01月25[]>
  So we should use SimpleDateFormat as a workaround for this bug at present.